#pragma config(Sensor, S1,     sound,          sensorSoundDBA)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int clap = 0;
void flipSwitch ()
{
	resetMotorEncoder(motorA);
	while(getMotorEncoder(motorA) < 180)
		{
			motor[motorA] = 50;
		}
}

task main()
{
	while(true)
	{
		while(SensorValue(sound)< 60)
		{
			motor[motorA]=0;
		}
			clearTimer(timer1);
			get



		while(SensorValue(sound) > 60)
		{
		}



	}

}
