#pragma config(Sensor, S1,     sound,          sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int clap = 0;

	while(true)
	{
		while(SensorValue(sound) > 0)
		{
			displayBigTextLine(4, "sound: %d", SensorValue(sound));

			if(SensorValue(sound) > 60)
			{
				clap = clap + 1;
				wait1Msec(100);
			}

			while(clap == 1)
			{
				if(SensorValue(sound) > 60)
				{
					clap = clap + 1;
					wait1Msec(100);
				}
			}

			if(clap == 2)
			{
				while(getMotorEncoder(motorA) < 180)
				{
					motor[motorA] = 50;
				}
				motor[motorA] = 0;
				clap = 0;
				resetMotorEncoder(motorA);
			}
		}
	}
}
