#pragma config(Sensor, S1,     sound,          sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int clap = 0;

void flipSwitch()
{
		resetMotorEncoder(motorA);
		while(getMotorEncoder(motorA) < 180)
			{
				motor[motorA] = 50;
			}

		motor[motorA] = 0;
		clap = 0;
		resetMotorEncoder(motorA)
}

void doNothingInSilence()
{
	while(SensorValue(sound) < 60)
	{
	}
}

void doNothingInSound()
{
	while(SensorValue(sound) > 59)
	{
	}
}


task main()
{
	while(true)
	{
		while(SensorValue(sound) > 0)
		{
			displayBigTextLine(4, "sound: %d", SensorValue(sound));

			doNothingInSilence();

			doNothingInSound();

			clearTimer(timer1);

			doNothingInSilence();

			if(getTimerValue(timer1) < 1001)
			{
				flipSwitch();
			}
		}
	}
}
