#pragma config(Sensor, S1,     sound,          sensorSoundDBA)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void edge ()
{
	while(SensorValue(sound) < 60)
	{
		motor[motorA] = 0;
	}

	if(SensorValue(sound) > 60)
	{
		clearTimer(timer1);
	}
	if(getTimerValue(timer1)<=1000)
	{
		if(SensorValue(sound) > 60)
		{
			motor[motorA] = 50;
			if(getMotorEncoder(motorA) > 180)
			{
				// use while statment
				motor[motorA] = 0;
				clearTimer(timer1);
			}
		}

	}
}



task main()
{
	while(true)
	{
		edge();
	}
}
